using System.Text.Json.Nodes;
using Haoyue.Runtime.Configuration;

namespace Haoyue.Tests;

public sealed class ConfigTests : IDisposable
{
    private readonly string _dir = Path.Combine(Path.GetTempPath(), "haoyue-tests", Guid.NewGuid().ToString("N"));

    public ConfigTests() => Directory.CreateDirectory(_dir);

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch (IOException) { }
    }

    private ConfigStore NewStore() => new(
        Path.Combine(_dir, "config.json"),
        Path.Combine(_dir, "state.json"));

    [Fact]
    public void MissingConfig_CreatesDefaults_AndPersists()
    {
        var store = NewStore();
        Assert.True(File.Exists(Path.Combine(_dir, "config.json")));

        // First-run seed is generated by serializing the code-defined defaults.
        // Providers and model routing are intentionally empty so users must create their own.
        Assert.Empty(store.Config.Providers);
        Assert.Empty(store.Config.Routing.Fallback);
        Assert.Equal(40, store.Config.Agent.MaxSteps);
        Assert.True(store.Config.Routing.FailoverEnabled); // failover default on
        Assert.False(store.Config.Routing.DeepSeekOptimizationEnabled); // DeepSeek optimization default off
    }

    [Fact]
    public void SaveAndReload_RoundTripsProvidersAndModel()
    {
        var store = NewStore();
        store.Config.Providers.Add(new ProviderConfig
        {
            Id = "test",
            Kind = "openai",
            BaseUrl = "https://example.test/v1",
            ApiKey = "config-secret",
            Models = [new ModelConfig { Id = "m1", Alias = "one", ContextWindow = 9000, InputPricePerMTok = 1.5m }],
        });
        store.Config.Provider = "test";
        store.Config.Model = "m1";
        store.Config.Temperature = 0.3;
        store.Save();

        var reloaded = NewStore();
        var provider = Assert.Single(reloaded.Config.Providers, p => p.Id == "test");
        Assert.Equal("test", provider.Id);
        Assert.Equal("config-secret", provider.ApiKey);
        Assert.Equal(9000, provider.Models[0].ContextWindow);
        Assert.Equal("one", provider.Models[0].Alias);
        Assert.Equal(1.5m, provider.Models[0].InputPricePerMTok);
        Assert.Equal("test", reloaded.Config.Provider);
        Assert.Equal("m1", reloaded.Config.Model);
        Assert.Equal(0.3, reloaded.Config.Temperature);
    }

    [Fact]
    public void Routing_FailoverEnabled_RoundTrips()
    {
        var store = NewStore();
        store.Config.Routing.FailoverEnabled = false;
        store.Save();

        var reloaded = NewStore();
        Assert.False(reloaded.Config.Routing.FailoverEnabled);
    }

    [Fact]
    public void Save_PreservesUnchangedFieldsWrittenConcurrentlyByAnotherProcess()
    {
        // Simulates CLI (storeA) and daemon (storeB) editing different fields of the
        // shared config.json: the last saver must not clobber the other writer's field.
        var storeA = NewStore();
        var storeB = NewStore();
        storeA.Config.Model = "model-a";
        storeA.Save();

        storeB.Reload(); // baseline = disk content written by A
        storeB.Config.Agent.MaxSteps = 77;
        storeB.Save();

        storeA.Save(); // A changed nothing locally → B's MaxSteps must survive

        var verifier = NewStore();
        Assert.Equal("model-a", verifier.Config.Model);
        Assert.Equal(77, verifier.Config.Agent.MaxSteps);
    }

    [Fact]
    public void Save_LocallyChangedFields_WinOverConcurrentWriter()
    {
        var storeA = NewStore();
        var storeB = NewStore();
        storeB.Config.Model = "model-b";
        storeB.Save();

        storeA.Reload(); // A sees model-b as its baseline
        storeA.Config.Model = "model-a2"; // A changed the same field → A wins
        storeA.Config.Agent.MaxSteps = 55;
        storeA.Save();

        var verifier = NewStore();
        Assert.Equal("model-a2", verifier.Config.Model);
        Assert.Equal(55, verifier.Config.Agent.MaxSteps);
    }

    [Fact]
    public void Save_LeavesNoTempFileResidue()
    {
        var store = NewStore();
        store.Config.Model = "x";
        store.Save();
        store.SaveState();

        Assert.Empty(Directory.GetFiles(_dir, "*.tmp", SearchOption.TopDirectoryOnly));
    }

    [Fact]
    public void Routing_DeepSeekOptimization_RoundTrips()
    {
        var store = NewStore();
        store.Config.Routing.DeepSeekOptimizationEnabled = true;
        store.Save();

        var reloaded = NewStore();
        Assert.True(reloaded.Config.Routing.DeepSeekOptimizationEnabled);
    }

    [Fact]
    public void Reset_RestoresFactoryDefaults_AndPersists()
    {
        var store = NewStore();
        store.Config.Providers.Add(new ProviderConfig
        {
            Id = "custom",
            Kind = "openai",
            BaseUrl = "https://custom.example/v1",
            ApiKey = "reset-me",
        });
        store.Config.Routing.FailoverEnabled = false;
        store.State.DisabledSkills["custom-skill"] = "";
        store.Save();
        store.SaveState();

        store.Reset();

        Assert.DoesNotContain(store.Config.Providers, provider => provider.Id == "custom");
        Assert.Empty(store.Config.Providers);
        Assert.Empty(store.Config.Routing.Fallback);
        Assert.True(store.Config.Routing.FailoverEnabled);
        Assert.Empty(store.State.DisabledSkills);

        var reloaded = NewStore();
        Assert.True(reloaded.Config.Routing.FailoverEnabled);
        Assert.Empty(reloaded.State.DisabledSkills);
    }

    [Fact]
    public void CorruptConfig_FallsBackToDefaults_SetsAnomaly_AndCreatesBackup()
    {
        var configFile = Path.Combine(_dir, "config.json");
        File.WriteAllText(configFile, "{ not json !!");
        var store = NewStore();
        Assert.Equal(40, store.Config.Agent.MaxSteps);
        Assert.True(store.HasAnomaly);
        Assert.NotNull(store.AnomalyDetail);
        Assert.NotNull(store.BackupConfigFile);
        Assert.True(File.Exists(store.BackupConfigFile));
        Assert.Equal("{ not json !!", File.ReadAllText(store.BackupConfigFile));
        Assert.Equal("{ not json !!", File.ReadAllText(configFile));

        store.Reset();
        Assert.False(store.HasAnomaly);
        Assert.Null(store.AnomalyDetail);
        Assert.Null(store.BackupConfigFile);
    }

    [Fact]
    public void MigrateLegacyProfiles_ExtractsDefaultProfileToTopLevel()
    {
        var legacyJson = """
        {
          "activeProfile": "default",
          "profiles": {
            "default": {
              "provider": "openai-main",
              "model": "gpt-4o",
              "temperature": 0.7
            }
          }
        }
        """;
        File.WriteAllText(Path.Combine(_dir, "config.json"), legacyJson);
        var store = NewStore();
        Assert.Equal("openai-main", store.Config.Provider);
        Assert.Equal("gpt-4o", store.Config.Model);
        Assert.Equal(0.7, store.Config.Temperature);
    }

    [Fact]
    public void ResolveApiKey_UsesOnlyExplicitConfigurationValue()
    {
        Environment.SetEnvironmentVariable("HAOYUE_TEST_KEY", "from-env");
        try
        {
            Assert.Null(new ProviderConfig().ResolveApiKey());
            Assert.Equal("direct", new ProviderConfig { ApiKey = "direct" }.ResolveApiKey());
        }
        finally
        {
            Environment.SetEnvironmentVariable("HAOYUE_TEST_KEY", null);
        }
    }

    [Fact]
    public void CaptureDirtyPatch_IncludesOnlyChangedLeaves()
    {
        var store = NewStore();
        var providerId = "p-" + Guid.NewGuid().ToString("N");
        store.Config.Providers = [new ProviderConfig { Id = providerId, Kind = "openai" }];
        store.Config.Agent.Mode = "edit";
        store.Save(); // baseline established

        // Unchanged → null, so a delegated save has nothing to send.
        Assert.Null(store.CaptureDirtyPatch());

        store.Config.Agent.Mode = "auto";
        store.Config.Provider = providerId;
        var patch = store.CaptureDirtyPatch();
        Assert.NotNull(patch);
        // Nested change stays nested; untouched siblings (e.g. agent.maxSteps) stay out.
        var agent = Assert.IsType<JsonObject>(patch["agent"]);
        Assert.Equal("auto", agent["mode"]?.GetValue<string>());
        Assert.Null(agent["maxSteps"]);
        Assert.Equal(providerId, patch["provider"]?.GetValue<string>());
    }

    [Fact]
    public void ApplyPatch_DeepMergesWithoutClobberingSiblings()
    {
        var store = NewStore();
        store.Config.Agent.Mode = "plan";
        store.Config.Agent.MaxSteps = 20;
        store.Save();

        // A delegated patch from the other process carries only its own edits.
        store.ApplyPatch(new JsonObject
        {
            ["agent"] = new JsonObject { ["mode"] = "edit" },
            ["temperature"] = 0.5,
        });

        Assert.Equal("edit", store.Config.Agent.Mode);
        Assert.Equal(20, store.Config.Agent.MaxSteps); // sibling survives the merge
        Assert.Equal(0.5, store.Config.Temperature);

        // And the patch landed on disk too.
        var reloaded = NewStore();
        Assert.Equal("edit", reloaded.Config.Agent.Mode);
        Assert.Equal(20, reloaded.Config.Agent.MaxSteps);
    }
}
