// 由 scripts/generate-contract.mjs 从 contracts/daemon-contract.json 生成，禁止手工编辑。
// 契约版本 1.0（协议 2.2）。重新生成：pnpm sync:contract

export const DAEMON_PROTOCOL_VERSION = '2.2' as const
export const DAEMON_CONTRACT_VERSION = '1.0' as const

export const DAEMON_ERROR_CODES = [
  'requestFailed',
  'invalidRequest',
  'unknownMethod',
  'invalidParams',
  'notFound',
  'conflict',
  'unauthorized',
  'versionMismatch',
  'internalError',
] as const

/** daemon error 事件 details.code 的契约取值；旧版 daemon 未携带时回退为 unknown。 */
export type DaemonErrorCode = (typeof DAEMON_ERROR_CODES)[number] | 'unknown'

export const DAEMON_STREAM_EVENTS = [
  'delta',
  'thinking',
  'steer',
  'image_view',
  'status',
  'tool_start',
  'tool_done',
  'file_diff',
  'model_start',
  'usage',
  'workflow',
  'plan_update',
] as const

export const DAEMON_TERMINAL_EVENTS = [
  'pong',
  'result',
  'done',
  'cancelled',
  'error',
  'bye',
] as const

export const DAEMON_BROADCAST_EVENTS = [
  'schedule.updated',
  'schedule.upcoming',
  'evolution.reflected',
  'mcp.updated',
  'turn.interrupted',
] as const

export const DAEMON_EVENT_NAMES = [
  'delta',
  'thinking',
  'steer',
  'image_view',
  'status',
  'tool_start',
  'tool_done',
  'file_diff',
  'model_start',
  'usage',
  'workflow',
  'plan_update',
  'pong',
  'result',
  'done',
  'cancelled',
  'error',
  'bye',
  'schedule.updated',
  'schedule.upcoming',
  'evolution.reflected',
  'mcp.updated',
  'turn.interrupted',
] as const

export type DaemonEventName = (typeof DAEMON_EVENT_NAMES)[number]

export const DAEMON_METHODS = [
  'ping',
  'protocol.info',
  'contract.export',
  'events.recent',
  'shutdown',
  'chat',
  'agent.runTurn',
  'agent.steer',
  'agent.cancel',
  'agent.undo',
  'agent.interrupted',
  'feedback.turn',
  'workspace.get',
  'workspace.open',
  'workspace.init',
  'agent.mode.get',
  'agent.mode.switch',
  'config.save',
  'config.status',
  'config.rebuild',
  'routing.get',
  'routing.set',
  'advanced.get',
  'advanced.set',
  'prompt.optimize',
  'provider.list',
  'provider.upsert',
  'provider.use',
  'provider.remove',
  'provider.test',
  'provider.models.fetch',
  'local.models',
  'model.list',
  'model.catalog',
  'model.switch',
  'model.test',
  'model.status',
  'model.update',
  'schedule.list',
  'schedule.create',
  'schedule.update',
  'schedule.toggle',
  'schedule.delete',
  'schedule.run',
  'mcp.list',
  'mcp.upsert',
  'mcp.remove',
  'mcp.reload',
  'skill.list',
  'skill.import',
  'skill.toggle',
  'skill.official.list',
  'skill.official.install',
  'expert.list',
  'knowledge.list',
  'knowledge.search',
  'knowledge.save',
  'knowledge.delete',
  'knowledge.import',
  'memory.get',
  'memory.save',
  'rules.list',
  'rules.save',
  'usage.get',
  'usage.timeline',
  'session.list',
  'session.search',
  'session.get',
  'session.truncate',
  'session.fork',
  'session.update',
  'session.archive',
  'session.delete',
  'session.resume',
  'session.new',
  'project.list',
  'project.upsert',
  'project.remove',
  'evolution.inspect',
  'evolution.reflect',
  'evolution.pending-list',
  'evolution.decide',
  'doctor',
  'doctor.run',
  'lock.list',
  'factory.reset',
] as const

export type DaemonMethod = (typeof DAEMON_METHODS)[number]
